### ISSUE TITLE
MangaBuddy broken?

### ISSUE THREAD

**Issue by Error404-NameNotFound** [TheNetsky/extensions-buddycomplex#7]
**Describe the bug**
Blank page when you try to go to MangaBuddy source/tab. Same thing happens when you go to their website by clicking the cloud icon. You will see a long error when you try to refresh the source.

**To Reproduce**
1. Go to External Sources in settings.
2. Click on “Browse BubbyComplex Extensions (0.6)” if you have it installed already.
3. Click refresh on MangaBuddy source (if it’s installed)

**Expected behavior**
I expected for the website to work and show something about cloudflare.

**Screenshots/Video**
![5F635325-6060-4C58-9A97-E5C7CDE10DC1](https://user-images.githubusercontent.com/23133571/195183857-871e7594-a21a-4465-8c08-c5376a17d565.jpeg)
![2C6124EA-1BC9-4FD9-8716-69272738CE6F](https://user-images.githubusercontent.com/23133571/195183900-bdc8b5a1-6de6-4242-9f1d-f36d10da77c0.jpeg)
![8BDB448C-6A08-48AD-8F59-B5C06ECDFC92](https://user-images.githubusercontent.com/23133571/195183960-3bd199f3-dc55-4110-89b7-56f855e82330.jpeg)

**App version**
- v0.7-r46

**Source WITH source version**
- MangaBuddy 1.1.2

**Additional context**
Not sure if it’s a source problem or just me.

**Comment by TheNetsky** [comment]
Issue on your end, website likely block in your country/isp.

Works fine for me, use a VPN perhaps.
