### ISSUE TITLE
Mangamad won’t load manga

### ISSUE THREAD

**Issue by ashathe** [TheNetsky/extensions-buddycomplex#8]
Describe the bug
The Mangamad source looks broken. No chapters can be opened
![18C02FA5-5B63-4314-8EB7-761AA98A73A7](https://user-images.githubusercontent.com/7953905/206872667-f66cd774-c0e2-443e-bebb-6fc0f65307d6.png)

To Reproduce

Go to Discover
Click on Mangamad tab
See that there are chapters in the index, but click on a manga and see that nothing loads
Expected behavior
When you open the app and go to the tab belonging to Mangamad in Discover area, load a manga and read it

**Comment by TheNetsky** [comment]
Source removed.
