### ISSUE TITLE
MangaBuddy not working

### ISSUE THREAD

**Issue by Error404-NameNotFound** [TheNetsky/extensions-buddycomplex#9]
**Describe the bug**
MangaBuddy is not working anymore. I can’t read manga from MangaBuddy. I get a very long error message when I tried to read manga from MangaBuddy today.

**To Reproduce**
1. Go to library.
2. Click on manga with MangaBuddy source.
3. Scroll down and select a chapter to read.
4. See error.

**Expected behavior**
I expected to read manga instead of reading nothing but error messages.

**Screenshots/Video**
![6D4C23BB-55BF-4666-8CED-8E5C287D454C](https://user-images.githubusercontent.com/23133571/226064156-b7b1bc84-b47a-4cc6-8052-d070240859c6.jpeg)

**App version**
- v0.7-r46

**Source WITH source version**
- MangaBuddy 1.1.2

**Additional context**
I’m not sure if it’s only happening to me or not since no one else has posted an issue with MangaBuddy today.

**Comment by TheNetsky** [comment]
No longer being maintained also this is the wrong repo.
